name: Java CI

on:
  push:
    branches:
      - main # Runs on pushes to the 'main' branch
  pull_request:
    branches:
      - main # Runs on pull requests targeting the 'main' branch

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Check out the code
      - name: Checkout repository
        uses: actions/checkout@v3

      # Step 2: Set up Java
      - name: Set up Java 21
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin' # Options are: 'zulu', 'temurin', 'adopt', etc.
          java-version: 17

      # Step 4: Build and test the project
      - name: Build and Test with Maven
        run: mvn clean install

      # Optional: Upload test results
      - name: Upload test results
        if: always() # Run even if the build/test fails
        uses: actions/upload-artifact@v3
        with:
          name: test-results
          path: target/surefire-reports/*.xml

      - name: Checkstyle Validation (Optional)
        run: mvn checkstyle:check -Dcheckstyle.config.location=checkstyles.xml