name: Java CI with Test Reports

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout repository code
      - name: Checkout repository
        uses: actions/checkout@v3

      # Step 2: Set up Java environment
      - name: Set up Java 21
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 21

      # Step 4: Build and test the project
      - name: Build and run tests
        run: mvn clean install

      # Step 5: Generate Surefire test report (HTML)
      - name: Generate Surefire Test Report
        run: |
          mvn surefire-report:report-only
          mvn site -DgenerateReports=false
        # Generates HTML reports

      # Step to debug directory structure
      - name: List generated site files
        run: ls -R target
      # Step to move surefire-report.html to index.html
#      - name: Prepare Pages for Deployment
#        run: |
#          mv target/site/surefire-report.html target/site/index.html

      # Step 6: Upload Test Results as an Unzipped Artifact
      - name: Upload test results (uncompressed)
        uses: actions/upload-pages-artifact@v1
        with:
          path: target/site

  deploy-test-results:
    needs: build-and-test
    runs-on: ubuntu-latest
    steps:
      # Step 1: Checkout repository code
      - name: Checkout repository
        uses: actions/checkout@v3

      # Step 2: Deploy to GitHub Pages
      - name: Deploy Test Reports to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: target/site