name: Java CI with Test Reports

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout repository code
      - name: Checkout repository
        uses: actions/checkout@v3

      # Step 2: Set up Java environment
      - name: Set up Java 21
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 21

      # Step 3: Build and test the project
      - name: Build and run tests
        run: mvn clean install -B -fae --no-transfer-progress -Dspring.profiles.active=dev -DskipTests=false